# Generated by Django 2.2.3 on 2019-07-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AlterField(
            model_name='entry',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
