# Generated by Django 2.2.3 on 2019-07-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190724_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
